### ISSUE TITLE
Apk de

### ISSUE THREAD

**Issue by anirudhgupta109** [divadsn/Jukebox#1]
Gib apk

**Comment by divadsn** [comment]
@anirudhgupta109 There is no APK for you 🙈

**Comment by anirudhgupta109** [comment]
@divadsn But sir, apk i want

**Comment by anirudhgupta109** [comment]
@divadsn Cool app

**Comment by divadsn** [comment]
@anirudhgupta109 Sir, you can download Replaio for Android and listen to Jukebox FM there.

**Comment by anirudhgupta109** [comment]
@divadsn Gib link

**Comment by divadsn** [comment]
https://play.google.com/store/apps/details?id=com.hv.replaio
